ingress api change for microk8s 1.23
charmed-osm/ops-lib-charmed-osm pull request #23
Opened 2022-01-24 18:37 UTC by gatici

Signed-off-by: aticig <gulsum.atici@canonical.com>

2022-01-25 08:45 UTC, gatici commented
This change fixes the error "k8s pod-spec-set charm erroring with "server could not find the requested resource" in microk8s version 1.22 and higher versions. We are changing ingress resource structure to become compatible with api version v1 according to "https://bugs.launchpad.net/juju/+bug/1939278"

2022-01-25 09:48 UTC, davigar15 requested changes
Please, comment if you have confirmed the patch works in K8s 1.23

2022-01-25 09:48 UTC, davigar15 commented on opslib/osm/pod.py
> +    def add_rule(self, hostname: str, service_name, path_type, port, path: str = "/",):
give it a default value of "Prefix". This way we don't need to change every charm.

2022-01-25 09:51 UTC, davigar15 commented on opslib/osm/pod.py
> +    def add_rule(self, hostname: str, service_name, path_type, port, path: str = "/",):
also, execute `black opslib/`.

2023-09-01 09:01 UTC, gatici commented
This is not valid anymore.

2023-09-01 09:01 UTC, closed without merging